name: Security Analysis Smart Contract
on:
  workflow_call:
    inputs:
      # Tools to use
      ## Slither
      ### https://github.com/crytic/slither/wiki/Usage#configuration-file
      slither:
        required: true
        type: boolean
        default: true
        description: "Enable slither"
      slither-config:
        required: false
        type: string
        default: "./security-configs/slither.conf"

      # Execution inputs
      ## Workflow runner
      workflow-runner:
        required: false
        type: string
        default: "ubuntu-latest"
        description: "Workflow runner"
      template-ref:
        required: false
        type: string
        default: "feat/sc-analysis"
        description: "template branch ref"

      # Results inputs
      ## Results
      result-path:
        required: false
        type: string
        default: "results"
        description: "results path"
      ## Artifact configuration
      artifact-name:
        required: false
        type: string
        default: "results-artifacts"
        description: "Name for results artifacts"
      artifact-retention-days:
        required: false
        type: number
        default: 7
        description: "Artifact retention period in days"

      #Claude
      ## Template
      claude-template:
        required: false
        type: string
        default: "../templates/.github/workflows/sc-analyzer/default_configs/claude/claude.md"
        description: "claude template"

      # General options
      environment:
        required: false
        type: string
        default: "test"
        description: "environment to use"

#    outputs:
#      artifact-id:
#        description: "ID of uploaded build artifact"
#        value: ${{ jobs.build.outputs.artifact-id }}

# Concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  # add build step?

  slither:
    if: ${{ inputs.slither }}

    #runs-on: ${{ inputs.workflow-runner }}
    runs-on: [self-hosted, claude]
    container:
      image: ubuntu:latest

    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      # Checkout everything
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo
          submodules: "recursive"
